"use strict";
// docs-view.js に切り出しやすい領域
const DocsView = ({ data, isExporting, updateCurrentData, openTextInput, setDeleteTabModal, activeTab, formatDate }) => {
    return (React.createElement("div", { className: `flex flex-col gap-6 relative bg-white rounded-xl shadow-inner p-4 sm:p-8 min-h-[80vh] font-pop` },
        React.createElement("div", { className: "flex flex-col md:flex-row justify-between items-start sm:items-end border-b-[3px] border-gray-800 pb-3 mt-4 gap-4" },
            React.createElement("div", { className: "flex items-center gap-2" },
                !isExporting && (React.createElement("div", { className: "flex flex-col gap-1" },
                    React.createElement("div", { className: "flex items-center justify-between" },
                        React.createElement("span", { className: "text-xs font-bold text-gray-500" }, "\u30BF\u30D6\u540D"),
                        React.createElement("button", { type: "button", onClick: () => setDeleteTabModal({ isOpen: true, targetId: activeTab }), className: "text-xs text-red-500 hover:text-red-700 hover:bg-red-50 px-1 py-0.5 rounded transition-colors flex items-center gap-0.5", title: "\u3053\u306E\u30BF\u30D6\u3092\u524A\u9664" },
                            React.createElement("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-3.5 w-3.5", viewBox: "0 0 20 20", fill: "currentColor" },
                                React.createElement("path", { fillRule: "evenodd", d: "M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z", clipRule: "evenodd" })),
                            "\u30BF\u30D6\u3092\u524A\u9664")),
                    React.createElement("div", { onClick: () => openTextInput('タブ名', data.tabLabel, v => updateCurrentData(prev => ({ ...prev, tabLabel: v }))), className: "text-sm font-bold border-2 border-gray-300 rounded px-2 py-1 w-32 bg-gray-50 text-gray-700 cursor-pointer hover:bg-gray-100 min-h-[2rem] flex items-center" }, data.tabLabel))),
                React.createElement("h1", { className: "text-xl sm:text-2xl md:text-3xl font-black text-gray-900 tracking-wider ml-2" },
                    "\u79C1\u306E\u5C65\u6B74\u66F8\uFF5E",
                    data.tabLabel)),
            React.createElement("div", { className: "flex flex-col items-end gap-2 ml-auto" },
                data.updatedAt && (React.createElement("span", { className: "text-xs sm:text-sm font-bold text-gray-500 shrink-0" },
                    "\u6700\u7D42\u66F4\u65B0: ",
                    formatDate(data.updatedAt))),
                !isExporting && (React.createElement("button", { type: "button", onClick: () => updateCurrentData(prev => ({ ...prev, records: [...(prev.records || []), { id: Date.now(), date: '', title: '', description: '' }] })), className: "bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-6 rounded-full shadow-md active:scale-95 transition-transform" }, "\u8A18\u9332\u3092\u8FFD\u52A0")))),
        React.createElement("div", { className: "flex flex-col gap-4 mt-4" },
            (data.records || []).map((rec, index) => (React.createElement("div", { key: rec.id, className: "relative bg-gray-50 border-2 border-gray-200 rounded-xl p-4 flex flex-col sm:flex-row gap-4 group" },
                !isExporting && React.createElement("button", { type: "button", onClick: () => updateCurrentData(prev => ({ ...prev, records: prev.records.filter(r => r.id !== rec.id) })), className: "absolute -top-3 -right-3 bg-white border-2 border-red-400 text-red-500 hover:bg-red-50 w-8 h-8 rounded-full flex items-center justify-center font-bold opacity-0 group-hover:opacity-100 z-20 transition-opacity shadow-sm" }, "\u00D7"),
                React.createElement("div", { className: "flex flex-col sm:w-1/4 gap-2" },
                    React.createElement("span", { className: "text-xs font-bold text-gray-500" }, "\u53D7\u8CDE\u65E5\u6642\u30FB\u5E74\u6708"),
                    isExporting ? (React.createElement("div", { className: "font-bold text-gray-800 text-lg border-b-2 border-gray-300 pb-1" }, rec.date)) : (React.createElement("div", { onClick: () => openTextInput('受賞日時・年月', rec.date, v => { updateCurrentData(prev => { const newRecs = [...prev.records]; newRecs[index].date = v; return { ...prev, records: newRecs }; }); }), className: "p-2 border border-gray-300 rounded font-bold text-gray-700 bg-white cursor-pointer hover:bg-gray-50 min-h-[2.5rem]" }, rec.date || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u4F8B\uFF1A2024\u5E7410\u6708")))),
                React.createElement("div", { className: "flex flex-col sm:w-3/4 gap-2" },
                    React.createElement("span", { className: "text-xs font-bold text-gray-500" }, "\u53D7\u8CDE\u540D\u30FB\u8A18\u9332"),
                    isExporting ? (React.createElement("div", { className: "font-bold text-gray-900 text-xl border-b-2 border-gray-300 pb-1" }, rec.title)) : (React.createElement("div", { onClick: () => openTextInput('受賞名・記録', rec.title, v => { updateCurrentData(prev => { const newRecs = [...prev.records]; newRecs[index].title = v; return { ...prev, records: newRecs }; }); }), className: "p-2 border border-gray-300 rounded font-bold text-gray-900 bg-white text-lg cursor-pointer hover:bg-gray-50 min-h-[3rem]" }, rec.title || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u4F8B\uFF1A\u3007\u3007\u5927\u4F1A \u512A\u52DD"))),
                    React.createElement("span", { className: "text-xs font-bold text-gray-500 mt-2" }, "\u8A73\u7D30\u30FB\u30E1\u30E2"),
                    isExporting ? (React.createElement("div", { className: "font-medium text-gray-700 whitespace-pre-wrap" }, rec.description)) : (React.createElement("div", { onClick: () => openTextInput('詳細・メモ', rec.description, v => { updateCurrentData(prev => { const newRecs = [...prev.records]; newRecs[index].description = v; return { ...prev, records: newRecs }; }); }, true), className: "p-2 border border-gray-300 rounded font-medium text-gray-700 bg-white h-24 overflow-y-auto cursor-pointer hover:bg-gray-50 whitespace-pre-wrap" }, rec.description || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u304C\u3093\u3070\u3063\u305F\u3053\u3068\u3084\u611F\u60F3\u306A\u3069..."))))))),
            (data.records || []).length === 0 && (React.createElement("div", { className: "h-48 border-4 border-dashed border-gray-300 rounded-2xl flex flex-col items-center justify-center text-gray-400" },
                React.createElement("span", { className: "font-bold text-xl" }, "\u8A18\u9332\u3092\u8FFD\u52A0\u3057\u3066\u304F\u3060\u3055\u3044"))))));
};
