"use strict";
// profile-view.js に切り出しやすい領域
const ProfileView = ({ data, isExporting, profile, avatarUrl, basicStats, abilitiesGrid, handleProfileChange, openTextInput, getFontSize, onFontSizeChange, formatDate, fileInputRef, handleAvatarClick, handleFileChange, setIsCountryModalOpen, FLAGS, getProfileFontSize, getMuscleRank, openBasicStatModal, openSliderModal, getExportAbilityStyle, getAbilityStyle, handleCellClick, draggedIndex, handleDragStart, handleDragOver, handleDrop, handleDragEnd, showCopyButton, prevGradeName, onCopyPreviousAbilities }) => {
    var _a, _b;
    const profileNameFontSize = ((_a = data.fontSizes) === null || _a === void 0 ? void 0 : _a.profileName) || 'medium';
    const exportSize = isExporting ? 'xlarge' : profileNameFontSize;
    const exportBaseSize = isExporting ? 'xlarge' : 'large';
    const exportMediumSize = isExporting ? 'xlarge' : 'medium';
    return (React.createElement("div", { className: "flex flex-col bg-white rounded-xl shadow-inner p-4 sm:p-6 w-full font-pop" },
        React.createElement("div", { className: "w-full mb-6 px-1 flex flex-col sm:flex-row justify-between items-start sm:items-end border-b-[3px] border-gray-800 pb-3 gap-2 mt-4" },
            React.createElement("h1", { className: "text-xl sm:text-2xl md:text-3xl font-black text-blue-800 tracking-widest whitespace-nowrap" }, "\u79C1\u306E\u5C65\u6B74\u66F8\uFF5E\u30D7\u30ED\u30D5\u30A3\u30FC\u30EB"),
            data.updatedAt && (React.createElement("span", { className: "text-xs sm:text-sm font-bold text-gray-500" },
                "\u6700\u7D42\u66F4\u65B0: ",
                formatDate(data.updatedAt)))),
        React.createElement("div", { className: "flex flex-wrap lg:flex-nowrap items-end gap-4 w-full" },
            React.createElement("div", { className: "flex flex-col justify-end flex-grow lg:max-w-[320px] self-stretch" },
                React.createElement("div", { className: "bg-cyan-300 border-[3px] border-gray-500 px-5 py-2 rounded-md shadow-inner w-full relative z-10 flex items-center min-h-[3.5rem] group" }, isExporting ? (React.createElement("div", { className: `w-full font-black text-center whitespace-nowrap overflow-hidden text-gray-900 pb-3 ${getProfileFontSize('2xl', exportSize)}` }, profile.name)) : (React.createElement(React.Fragment, null,
                    React.createElement("div", { onClick: () => openTextInput('名前', profile.name, v => handleProfileChange('name', v)), className: `cursor-pointer hover:bg-white/50 w-full text-center text-gray-900 min-h-[3rem] font-black flex items-center justify-center ${getProfileFontSize('2xl', exportSize)}` }, profile.name || React.createElement("span", { className: "text-gray-500 font-normal text-base" }, "\u540D\u524D\u3092\u5165\u529B")),
                    React.createElement("div", { className: "absolute -top-3 right-0 opacity-40 hover:opacity-100 focus-within:opacity-100 transition-opacity z-20" },
                        React.createElement(FontSizeToggle, { value: profileNameFontSize, onChange: (v) => onFontSizeChange('profileName', v) })))))),
            React.createElement("div", { className: "flex border-[3px] border-gray-500 bg-white rounded-md overflow-hidden min-h-[3.5rem] mb-0 relative group" },
                React.createElement("div", { className: "w-32 border-r-[3px] border-gray-500 flex items-center justify-center relative" }, isExporting ? React.createElement("div", { className: `text-center font-bold whitespace-nowrap overflow-hidden text-gray-900 px-2 pb-2 ${getProfileFontSize('base', exportBaseSize)}` }, profile.team) : React.createElement("div", { onClick: () => openTextInput('出身地', profile.team, v => handleProfileChange('team', v)), className: `w-full text-center font-bold text-gray-900 cursor-pointer hover:bg-gray-100 min-h-[2rem] flex items-center justify-center ${getProfileFontSize('base', exportBaseSize)}` }, profile.team || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u51FA\u8EAB\u5730"))),
                React.createElement("div", { className: `relative w-24 flex items-center justify-center bg-white p-1 transition-colors ${!isExporting && 'cursor-pointer hover:bg-gray-100'}`, onClick: () => !isExporting && setIsCountryModalOpen(true) },
                    React.createElement("svg", { viewBox: "0 0 900 600", className: "w-full h-full border border-gray-300 rounded-sm pointer-events-none" }, ((_b = FLAGS[profile.country]) === null || _b === void 0 ? void 0 : _b.svg) || FLAGS['Japan'].svg))),
            React.createElement("div", { className: "w-28 h-28 bg-white border-[3px] border-gray-500 rounded-lg overflow-hidden flex-shrink-0 flex items-center justify-center relative cursor-pointer hover:opacity-80 group", onClick: handleAvatarClick },
                React.createElement("input", { type: "file", ref: fileInputRef, onChange: handleFileChange, accept: "image/*", className: "hidden" }),
                avatarUrl ? React.createElement("img", { src: avatarUrl, alt: "Avatar", className: "w-full h-full object-cover" }) : React.createElement("div", { className: "flex flex-col items-center justify-center text-blue-400 bg-blue-50/50 w-full h-full text-xs font-black" }, "\u753B\u50CF\u3092\u9078\u629E")),
            React.createElement("div", { className: "flex flex-col gap-3 flex-grow" },
                React.createElement("div", { className: "flex bg-white border-[3px] border-gray-500 rounded-md flex-grow min-h-[2.5rem] overflow-hidden relative group" },
                    React.createElement("div", { className: `bg-gray-100 text-gray-800 font-bold px-4 border-r-[3px] border-gray-500 flex items-center justify-center ${getProfileFontSize('base', exportBaseSize)}` }, "\u5B66\u6821"),
                    React.createElement("div", { className: "flex-grow flex items-center px-3 bg-white" }, isExporting ? React.createElement("div", { className: `w-full font-bold text-gray-900 whitespace-nowrap overflow-hidden pb-2 ${getProfileFontSize('base', exportBaseSize)}` }, profile.company) : React.createElement("div", { onClick: () => openTextInput('学校', profile.company, v => handleProfileChange('company', v)), className: `w-full font-bold text-gray-900 cursor-pointer hover:bg-gray-50 min-h-[2rem] flex items-center ${getProfileFontSize('base', exportBaseSize)}` }, profile.company || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u5B66\u6821\u540D\u3092\u5165\u529B")))),
                React.createElement("div", { className: "flex gap-3" },
                    React.createElement("div", { className: "flex bg-white border-[3px] border-gray-500 rounded-md flex-grow min-h-[2.5rem] overflow-hidden relative group" },
                        React.createElement("div", { className: `bg-gray-100 text-gray-800 font-bold px-3 border-r-[3px] border-gray-500 flex items-center justify-center ${getProfileFontSize('base', exportBaseSize)}` }, "\u5F79\u8077"),
                        React.createElement("div", { className: "flex-grow flex items-center px-3 bg-white" }, isExporting ? React.createElement("div", { className: `w-full font-bold text-gray-900 whitespace-nowrap overflow-hidden pb-2 ${getProfileFontSize('base', exportBaseSize)}` }, profile.role) : React.createElement("div", { onClick: () => openTextInput('役職', profile.role, v => handleProfileChange('role', v)), className: `w-full font-bold text-gray-900 cursor-pointer hover:bg-gray-50 min-h-[2rem] flex items-center ${getProfileFontSize('base', exportBaseSize)}` }, profile.role || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u5F79\u8077")))),
                    React.createElement("div", { className: "flex bg-white border-[3px] border-gray-500 rounded-md w-32 min-h-[2.5rem] overflow-hidden relative group" },
                        React.createElement("div", { className: `bg-gray-100 text-gray-800 font-bold px-2 border-r-[3px] border-gray-500 flex items-center justify-center ${getProfileFontSize('base', exportMediumSize)}` }, "\u5B66\u5E74"),
                        React.createElement("div", { className: "flex-grow flex items-center px-2 bg-white" }, isExporting ? React.createElement("div", { className: `w-full font-bold text-gray-900 text-center whitespace-nowrap overflow-hidden pb-2 ${getProfileFontSize('base', exportMediumSize)}` }, profile.years) : React.createElement("div", { onClick: () => openTextInput('学年', profile.years, v => handleProfileChange('years', v)), className: `w-full font-bold text-gray-900 text-center cursor-pointer hover:bg-gray-50 min-h-[2rem] flex items-center justify-center ${getProfileFontSize('base', exportMediumSize)}` }, profile.years || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u4F8B: \u9AD81"))))))),
        React.createElement("div", { className: "flex bg-white border-[3px] border-gray-500 rounded-md w-full relative overflow-hidden mt-4 min-h-[3.5rem] group" },
            React.createElement("div", { className: `bg-gray-100 text-gray-800 font-bold px-4 border-r-[3px] border-gray-500 flex items-center justify-center ${isExporting ? 'pb-3' : ''} ${getProfileFontSize('2xl', getFontSize('classGoal'))}` }, "\u5B66\u7D1A\u76EE\u6A19"),
            React.createElement("div", { className: "flex-grow flex items-center px-4 bg-white relative" }, isExporting ? React.createElement("div", { className: `w-full font-bold text-gray-900 whitespace-nowrap overflow-hidden pb-3 ${getProfileFontSize('2xl', getFontSize('classGoal'))}` }, profile.classGoal) : React.createElement(React.Fragment, null,
                React.createElement("div", { onClick: () => openTextInput('学級目標', profile.classGoal, v => handleProfileChange('classGoal', v)), className: `w-full font-bold text-gray-900 cursor-pointer hover:bg-gray-50 min-h-[2.5rem] flex items-center ${getProfileFontSize('2xl', getFontSize('classGoal'))}` }, profile.classGoal || React.createElement("span", { className: "text-gray-400 font-normal" }, "\u5B66\u7D1A\u76EE\u6A19\u3092\u5165\u529B")),
                React.createElement("div", { className: "absolute right-2 top-2 opacity-40 hover:opacity-100 focus-within:opacity-100 transition-opacity" },
                    React.createElement(FontSizeToggle, { value: getFontSize('classGoal'), onChange: (v) => onFontSizeChange('classGoal', v) }))))),
        React.createElement("hr", { className: "border-gray-500 my-4" }),
        React.createElement("div", { className: "flex flex-col md:flex-row gap-6" },
            React.createElement("div", { className: "w-full md:w-[340px] flex flex-col md:border-r-2 border-gray-300 pr-0 md:pr-4 py-1 shrink-0 relative group" },
                React.createElement("div", { className: "flex flex-col justify-between flex-grow gap-4" }, basicStats.slice(0, 3).map((stat, statIndex) => {
                    const iconMatch = stat.name.match(/^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)\s*/u);
                    const icon = iconMatch ? iconMatch[0] : '';
                    const text = stat.name.replace(/^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)\s*/u, '');
                    return (React.createElement("div", { key: stat.id, className: "flex flex-col gap-3 bg-white border-[3px] border-gray-500 rounded-xl p-3 shadow-sm" },
                        isExporting ? React.createElement("div", { className: "bg-yellow-50 border-2 border-gray-500 rounded-full w-full py-1.5 flex items-center justify-center shadow-sm" },
                            React.createElement("span", { className: `${getProfileFontSize('statTitle', 'xlarge')} font-extrabold text-gray-900 tracking-widest pb-2` },
                                icon,
                                " ",
                                text)) : React.createElement("button", { type: "button", onClick: () => openBasicStatModal(statIndex), className: "bg-yellow-50 border-2 border-gray-500 rounded-full w-full py-1.5 flex items-center justify-center shadow-sm hover:bg-yellow-100" },
                            React.createElement("span", { className: `${getProfileFontSize('statTitle', 'xlarge')} font-extrabold text-gray-900 tracking-widest pb-2` },
                                icon,
                                " ",
                                text)),
                        React.createElement("div", { className: "flex flex-col gap-2" }, stat.records.map((record, recordIndex) => {
                            const muscle = getMuscleRank(record.value);
                            return (React.createElement("div", { key: recordIndex, className: "flex items-center gap-2 h-8 px-1" },
                                React.createElement("span", { className: `font-bold text-gray-700 w-8 text-center shrink-0 ${getProfileFontSize('statMonth', 'xlarge')}` }, record.month),
                                React.createElement("div", { className: `flex items-center justify-center flex-shrink-0 transition-all ${muscle.boxClass} ${isExporting && record.value > 0 ? '-translate-y-2' : ''}` }, muscle.icon),
                                React.createElement("div", { className: "flex-grow flex items-center ml-1 relative" },
                                    React.createElement("div", { className: `relative w-full h-3 rounded-full bg-slate-100 ${!isExporting && 'cursor-pointer hover:h-4 transition-all'}`, style: { background: `linear-gradient(to right, #0ea5e9 ${record.value}%, #f1f5f9 ${record.value}%)` }, onClick: () => !isExporting && openSliderModal(statIndex, recordIndex, record.value, text, record.month) },
                                        React.createElement("div", { className: `absolute top-1/2 -mt-2.5 w-5 h-5 rounded-full bg-blue-500 shadow-md ${!isExporting && 'pointer-events-none'}`, style: { left: `calc(${record.value}% - 10px)` } }))),
                                React.createElement("div", { className: "w-8 text-right shrink-0" },
                                    React.createElement("span", { className: `font-black ${getProfileFontSize('statValue', 'xlarge')} ${muscle.textClass}` }, record.value))));
                        }))));
                }))),
            React.createElement("div", { className: "flex-grow flex flex-col gap-5 relative group" },
                !isExporting && React.createElement("div", { className: "absolute -top-3 right-0 opacity-40 hover:opacity-100 transition-opacity z-20" },
                    React.createElement(FontSizeToggle, { value: getFontSize('abilities'), onChange: (v) => onFontSizeChange('abilities', v), availableSizes: ['large', 'xlarge'] })),
                !isExporting && showCopyButton && (React.createElement("div", { className: "flex justify-end mb-[-10px] z-10 relative" },
                    React.createElement("button", { type: "button", onClick: onCopyPreviousAbilities, className: "px-4 py-1.5 bg-white border-[3px] border-indigo-400 text-indigo-700 hover:bg-indigo-50 rounded-full font-black shadow-sm transition-transform active:scale-95 flex items-center gap-1.5 text-xs sm:text-sm" },
                        React.createElement("svg", { xmlns: "http://www.w3.org/2000/svg", className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor" },
                            React.createElement("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2" })),
                        prevGradeName,
                        "\u306E\u7279\u6B8A\u30B9\u30AD\u30EB\u3092\u30B3\u30D4\u30FC"))),
                React.createElement("div", { className: "bg-cyan-50/60 rounded-xl p-4 border-[3px] border-gray-500 shadow-sm flex flex-col" },
                    React.createElement("div", { className: "flex items-center mb-4" }, isExporting ? React.createElement("div", { className: "bg-cyan-400 text-white font-black px-6 pt-1 pb-3 text-lg md:text-xl rounded-full shadow-sm flex items-center" }, "\u597D\u304D\u306A\u3053\u3068\u30FB\u5F97\u610F\u306A\u3053\u3068\u30FB\u81EA\u6162\u3057\u305F\u3044\u3053\u3068") : React.createElement("span", { className: "bg-cyan-400 text-white font-black px-6 pt-1 pb-3 text-lg md:text-xl rounded-full shadow-sm" }, "\u597D\u304D\u306A\u3053\u3068\u30FB\u5F97\u610F\u306A\u3053\u3068\u30FB\u81EA\u6162\u3057\u305F\u3044\u3053\u3068")),
                    React.createElement("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-3" }, abilitiesGrid.slice(0, 16).map((ability, index) => (React.createElement("div", { key: index, className: `${isExporting ? 'h-20' : 'h-12'} relative ${draggedIndex === index ? 'opacity-40' : ''}`, draggable: !isExporting && ability !== null, onDragStart: (e) => handleDragStart(e, index), onDragOver: handleDragOver, onDrop: (e) => handleDrop(e, index), onDragEnd: handleDragEnd }, ability ? (isExporting ? React.createElement("div", { className: `${getExportAbilityStyle(ability.type, getFontSize('abilities'))}` }, ability.name) : React.createElement("button", { type: "button", onClick: () => handleCellClick(index), className: `${getAbilityStyle(ability.type, getFontSize('abilities'))}` }, ability.name)) : (isExporting ? React.createElement("div", { className: "w-full h-full border-2 border-dashed border-gray-400 rounded-lg bg-white/60 flex items-center justify-center text-gray-400 text-3xl font-light shadow-sm" }, "\uFF0B") : React.createElement("button", { type: "button", onClick: () => handleCellClick(index), className: "w-full h-full border-2 border-dashed border-gray-400 rounded-lg bg-white hover:bg-gray-100 flex items-center justify-center text-gray-400 text-3xl font-light shadow-sm" }, "\uFF0B"))))))),
                React.createElement("div", { className: "bg-pink-50/60 rounded-xl p-4 border-[3px] border-gray-500 shadow-sm flex flex-col" },
                    React.createElement("div", { className: "flex items-center mb-4" }, isExporting ? React.createElement("div", { className: "bg-pink-400 text-white font-black px-6 pt-1 pb-3 text-lg md:text-xl rounded-full shadow-sm flex items-center" }, "\u82E6\u624B\u306A\u3053\u3068\u30FB\u624B\u4F1D\u3063\u3066\u307B\u3057\u3044\u3053\u3068") : React.createElement("span", { className: "bg-pink-400 text-white font-black px-6 pt-1 pb-3 text-lg md:text-xl rounded-full shadow-sm" }, "\u82E6\u624B\u306A\u3053\u3068\u30FB\u624B\u4F1D\u3063\u3066\u307B\u3057\u3044\u3053\u3068")),
                    React.createElement("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-3" }, abilitiesGrid.slice(16, 24).map((ability, i) => {
                        const index = i + 16;
                        return (React.createElement("div", { key: index, className: `${isExporting ? 'h-20' : 'h-12'} relative ${draggedIndex === index ? 'opacity-40' : ''}`, draggable: !isExporting && ability !== null, onDragStart: (e) => handleDragStart(e, index), onDragOver: handleDragOver, onDrop: (e) => handleDrop(e, index), onDragEnd: handleDragEnd }, ability ? (isExporting ? React.createElement("div", { className: `${getExportAbilityStyle(ability.type, getFontSize('abilities'))}` }, ability.name) : React.createElement("button", { type: "button", onClick: () => handleCellClick(index), className: `${getAbilityStyle(ability.type, getFontSize('abilities'))}` }, ability.name)) : (isExporting ? React.createElement("div", { className: "w-full h-full border-2 border-dashed border-gray-400 rounded-lg bg-white/60 flex items-center justify-center text-gray-400 text-3xl font-light shadow-sm" }, "\uFF0B") : React.createElement("button", { type: "button", onClick: () => handleCellClick(index), className: "w-full h-full border-2 border-dashed border-gray-400 rounded-lg bg-white hover:bg-gray-100 flex items-center justify-center text-gray-400 text-3xl font-light shadow-sm" }, "\uFF0B"))));
                    })))))));
};
